services:
  - xvfb
  
junit:
  stage: test
  script:
    - xvfb-run mvn -B package --file pom.xml
    - mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean package
  artifacts:
    paths:
      - target/team7_seng202*.jar 